export const SUBJECT_CATEGORIES = ['CORE', 'APPLIED', 'SPECIALIZED', 'OTHER']
export const SUBJECT_AREAS = [
  'MATHEMATICS',
  'SCIENCE',
  'LANGUAGE & LITERATURE',
  'SOCIAL SCIENCES',
  'ARTS & HUMANITIES',
  'TECHNOLOGY & ENGINEERING',
  'BUSINESS & ECONOMICS',
  'HEALTH & MEDICINE',
  'PHYSICAL EDUCATION & SPORTS',
  'VOCATIONAL & TECHNICAL',
]
export const ACADEMIC_LEVELS = [
  'GRADE1',
  'GRADE2',
  'GRADE3',
  'GRADE4',
  'GRADE5',
  'GRADE6',
  'GRADE7',
  'GRADE8',
  'GRADE9',
  'GRADE10',
  'GRADE11',
  'GRADE12',
]
export const SUBJECT_DIFFICULTIES = [
  'BEGINNER',
  'INTERMEDIATE',
  'ADVANCED',
  'EXPERT',
]
export const SUBJECT_TYPES = ['LECTURE', 'LABORATORY', 'SEMINAR', 'WORKSHOP']
